// Generated by CoffeeScript 1.10.0
var $, Backbone, Client;

require('coffee-script');

Backbone = require('backbone');

$ = require('jquery');

Client = Backbone.Model.extend({
  getURL: function(player) {
    var config, environment;
    config = this.get('config');
    environment = config.environment;
    if (player === "human") {
      return config[environment].url + config.humanMove;
    } else {
      return config[environment].url + config.computerMove;
    }
  },
  postUpdatedGame: function(data, model, onSuccess) {
    var url;
    url = this.getURL("computer");
    return $.ajax(url, {
      type: 'POST',
      context: model,
      crossOrigin: true,
      dataType: 'json',
      data: data,
      success: function(response) {
        return onSuccess(response, model);
      }
    });
  },
  getGameStatus: function(parameters, model, onSuccess) {
    var url;
    url = this.getURL("human") + parameters;
    return $.ajax(url, {
      crossOrigin: true,
      dataType: 'json',
      success: function(response) {
        return onSuccess(response, model);
      }
    });
  }
});

module.exports = Client;
