// Generated by CoffeeScript 1.10.0
var $, Backbone, Handlebars, HandlebarsCompiler;

$ = require('jquery');

Backbone = require('backbone');

Handlebars = require('handlebars');

HandlebarsCompiler = Backbone.Model.extend({
  load: function(templateName) {
    return $.ajax("../partials/" + templateName + ".html", {
      success: function(data) {
        var template;
        template = Handlebars.compile(data);
        $("#" + templateName + "-container").html(template);
        return $(".spot").height($(".spot").width());
      }
    });
  }
});

module.exports = HandlebarsCompiler;
