// Generated by CoffeeScript 1.10.0
var $, Backbone, Client, Game, GameView, Router;

$ = require('jquery');

Backbone = require('backbone');

Game = require('./models/Game');

GameView = require('./views/GameView');

Client = require('./models/Client');

Router = Backbone.Router.extend({
  routes: {
    '': 'main'
  },
  main: function() {
    var client, game, gameView;
    client = new Client;
    game = new Game({
      client: client
    });
    return gameView = new GameView({
      model: game
    });
  }
});

$(document).ready(function() {
  var router;
  return router = new Router;
});

e.history.start();
