// Generated by CoffeeScript 1.10.0
var $, Backbone, MockClient;

require('coffee-script');

Backbone = require('backbone');

$ = require('jquery');

MockClient = Backbone.Model.extend({
  postUpdatedGame: function(data, model, onSuccess) {
    var response;
    response = {
      board: ["X", "X", "X", "O", "", "", "O", "", ""],
      status: "player1Wins"
    };
    return onSuccess(response, model);
  }
});

module.exports = MockClient;
