// Generated by CoffeeScript 1.10.0
var $, Backbone, Client;

require('coffee-script');

Backbone = require('backbone');

$ = require('jquery');

Client = Backbone.Model.extend({
  defaults: {
    url: "http://stormy-savannah-24890.herokuapp.com/api/computer_move"
  },
  postUpdatedGame: function(data, model, onSuccess) {
    return $.ajax("http://stormy-savannah-24890.herokuapp.com/api/computer_move", {
      type: 'POST',
      context: model,
      crossOrigin: true,
      dataType: 'json',
      data: data,
      success: function(response) {
        return onSuccess(response, model);
      }
    });
  }
});

module.exports = Client;
