// Generated by CoffeeScript 1.10.0
var $, Backbone, GameView;

Backbone = require('backbone');

$ = require('jquery');

GameView = Backbone.View.extend({
  el: '#game',
  events: {
    'click .spot': 'move',
    'click #play-again': 'resetGame'
  },
  initialize: function() {
    $('.spot').height($('.spot').width());
    this.listenTo(this.model, 'change', this.render);
    this.listenTo(this.model, 'change:board', this.enableEmptySpots);
    return this.listenTo(this.model, 'change:status', this.checkGameStatus);
  },
  move: function(e) {
    var spotClicked;
    spotClicked = $(e.currentTarget);
    if (spotClicked.hasClass('enabled')) {
      this.disableAllSpots();
      return this.model.makeMove(spotClicked.attr('id'));
    }
  },
  render: function() {
    var i, j, marker, results, text;
    text = this.getStatusText(this.model.get('status'));
    $("#status").html(text);
    results = [];
    for (i = j = 0; j < 9; i = ++j) {
      marker = this.model.get('board')[i];
      results.push($('#' + i).html(this.getMarkerHTML(marker)));
    }
    return results;
  },
  checkGameStatus: function() {
    if (this.model.isOver()) {
      return this.endGame();
    }
  },
  endGame: function() {
    return this.disableAllSpots();
  },
  getStatusText: function(status) {
    switch (status) {
      case !this.model.get('isXTurn'):
        return "Computer is thinking...";
      case "in progress" && this.model.get('isXTurn'):
        return "Your turn!";
      case "tie":
        return "It's a tie!";
      case "player1Wins":
        return "X Wins!";
      case "player2Wins":
        return "O Wins!";
    }
  },
  getMarkerHTML: function(marker) {
    var htmlclass;
    htmlclass = marker === 'X' ? 'human-move' : 'computer-move';
    return "<span class=" + htmlclass + ">" + marker + "</span>";
  },
  resetGame: function() {
    this.model.resetAttributes();
    return this.enableAllSpots();
  },
  applyToAllSpots: function(functionToApply) {
    var $spot, i, j, results;
    results = [];
    for (i = j = 0; j < 9; i = ++j) {
      $spot = $('#' + i);
      results.push(functionToApply($spot, i));
    }
    return results;
  },
  enableAllSpots: function() {
    return this.applyToAllSpots(function($spot) {
      if (!$spot.hasClass('enabled')) {
        return $spot.addClass('enabled');
      }
    });
  },
  disableAllSpots: function() {
    return this.applyToAllSpots(function($spot) {
      if ($spot.hasClass('enabled')) {
        return $spot.removeClass('enabled');
      }
    });
  },
  enableEmptySpots: function() {
    var board;
    board = this.model.get('board');
    return this.applyToAllSpots(function($spot, i) {
      if (board[i] === "") {
        return $spot.addClass('enabled');
      }
    });
  }
});

module.exports = GameView;
