// Generated by CoffeeScript 1.10.0
var $, Backbone, GameView;

Backbone = require('backbone');

$ = require('jquery');

GameView = Backbone.View.extend({
  el: '#game',
  events: {
    'click .spot': 'move',
    'click #play-again': 'resetGame'
  },
  initialize: function() {
    $('.spot').height($('.spot').width());
    return this.listenTo(this.model, 'change', this.render);
  },
  move: function(e) {
    var spotClicked;
    spotClicked = $(e.currentTarget);
    if (spotClicked.hasClass('enabled')) {
      this.disableAllSpots();
      this.model.makeMove(spotClicked.attr('id'));
      this.model.endTurn();
      return this.enableEmptySpots();
    }
  },
  render: function() {
    var i, j, marker, results;
    results = [];
    for (i = j = 0; j < 9; i = ++j) {
      marker = this.model.get('board')[i];
      results.push($('#' + i).html(this.getMarkerHTML(marker)));
    }
    return results;
  },
  getMarkerHTML: function(marker) {
    var htmlclass;
    htmlclass = marker === 'X' ? 'human-move' : 'computer-move';
    return "<span class=" + htmlclass + ">" + marker + "</span>";
  },
  resetGame: function() {
    this.model.resetAttributes();
    return this.enableAllSpots();
  },
  applyToAllSpots: function(functionToApply) {
    var $spot, i, j, results;
    results = [];
    for (i = j = 0; j < 9; i = ++j) {
      $spot = $('#' + i);
      results.push(functionToApply($spot, i));
    }
    return results;
  },
  enableAllSpots: function() {
    return this.applyToAllSpots(function($spot) {
      if (!$spot.hasClass('enabled')) {
        return $spot.addClass('enabled');
      }
    });
  },
  disableAllSpots: function() {
    return this.applyToAllSpots(function($spot) {
      if ($spot.hasClass('enabled')) {
        return $spot.removeClass('enabled');
      }
    });
  },
  enableEmptySpots: function() {
    var board;
    board = this.model.get('board');
    return this.applyToAllSpots(function($spot, i) {
      if (board[i] === "") {
        return $spot.addClass('enabled');
      }
    });
  }
});

module.exports = GameView;
