// Generated by CoffeeScript 1.10.0
var $, Backbone, GameView;

Backbone = require('backbone');

$ = require('jquery');

GameView = Backbone.View.extend({
  el: '#game',
  events: {
    'click .spot': 'move',
    'click #play-again': 'resetGame'
  },
  initialize: function() {
    $('.spot').height($('.spot').width());
    return this.listenTo(this.model, 'change', this.render);
  },
  move: function(e) {
    var spotClicked;
    spotClicked = $(e.currentTarget);
    if (spotClicked.hasClass('enabled')) {
      spotClicked.removeClass('enabled');
      this.model.makeMove(spotClicked.attr('id'));
      return this.model.endTurn();
    }
  },
  render: function() {
    var i, j, marker, results;
    results = [];
    for (i = j = 0; j < 9; i = ++j) {
      marker = this.model.get('board')[i];
      results.push($('#' + i).html(this.getMarkerHTML(marker)));
    }
    return results;
  },
  getMarkerHTML: function(marker) {
    var htmlclass;
    htmlclass = marker === 'X' ? 'human-move' : 'computer-move';
    return "<span class=" + htmlclass + ">" + marker + "</span>";
  },
  resetGame: function() {
    this.model.resetAttributes();
    return this.enableAllSpots();
  },
  enableAllSpots: function() {
    var $spot, i, j, results;
    results = [];
    for (i = j = 0; j < 9; i = ++j) {
      $spot = $('#' + i);
      if (!$spot.hasClass('enabled')) {
        results.push($spot.addClass('enabled'));
      } else {
        results.push(void 0);
      }
    }
    return results;
  }
});

module.exports = GameView;
